<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StockLot;
use App\Models\StockDetail;
use App\Models\InboundTransaction;
use Carbon\Carbon;

class DummyStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $totalPallets = 120;
        $palletsPerLot = 8;
        $totalLots = ceil($totalPallets / $palletsPerLot);
        $startLotPrefix = 1; // Mulai dari Lot 1 s/d 15

        $palletCounter = 1;

        for ($i = 0; $i < $totalLots; $i++) {
            $lotPrefix = $startLotPrefix + $i;
            $fullLotNumber = $lotPrefix . '-' . Carbon::now()->format('dmY');

            // Bikin 1 StockLot per grup (8 palet)
            $stockLot = StockLot::create([
                'lot_number' => $fullLotNumber,
                'production_year' => date('Y'),
                'quality_type' => 'SIR 20 SW',
                'origin_unit' => 'SIR',
                'status' => 'blue', // Tersedia di gudang
                'inbound_at' => Carbon::now()->subDays($totalLots - $i), // Menjamin urutan FIFO yang benar secara kronologis
            ]);

            // Tentukan berapa palet di Lot ini (biasanya 8, kecuali sisa akhir pembagian jika total tidak habis dibagi 8)
            $palletsInThisLot = min($palletsPerLot, $totalPallets - $palletCounter + 1);

            $totalWeightKg = 0;

            for ($p = 0; $p < $palletsInThisLot; $p++) {
                // Format FDF 001, FDF 002, dst.
                $fdfNumber = 'FDF ' . str_pad($palletCounter, 3, '0', STR_PAD_LEFT);
                $baleCount = 36; // Default bale
                $weightKg = 1260; // Default kg (36 * 35kg)
                
                StockDetail::create([
                    'stock_lot_id' => $stockLot->id,
                    'packaging_type' => 'pallet',
                    'fdf_number' => $fdfNumber,
                    'pallet_number' => null, // Sudah tidak dipakai di UI
                    'bale_range' => '-',
                    'quantity_unit' => $baleCount,
                    'net_weight_kg' => $weightKg,
                ]);

                $totalWeightKg += $weightKg;
                $palletCounter++;
            }

            // Buat rekam jejak masuk gudang (InboundTransaction) agar lengkap di sejarah/laporan
            InboundTransaction::create([
                'stock_lot_id' => $stockLot->id,
                'ticket_number' => 'INB-DUMMY-' . $stockLot->id,
                'vehicle_plate' => 'BK ' . rand(1000, 9999) . ' ABC',
                'driver_name' => 'Supir Dummy ' . ($i + 1),
                'gross_weight' => $totalWeightKg,
                'tare_weight' => 0,
                'net_weight' => $totalWeightKg,
                'weigh_in_at' => $stockLot->inbound_at->subHours(2),
                'weigh_out_at' => $stockLot->inbound_at,
                'photo_path' => '',
                'ai_ocr_data' => json_encode(['note' => 'Generated by Dummy Seeder']),
            ]);
        }
    }
}
